version: '3.8'

services:
  # PHP service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: govi_m_app
    restart: unless-stopped
    working_dir: /var/www
    healthcheck:
      test: ["CMD", "php-fpm", "-t"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - govi-m
    volumes:
      - app-data:/var/www
    user: appuser

  # Nginx service
  webserver:
    build:
        context: ./nginx
        dockerfile: Dockerfile
    container_name: govi_m_webserver
    restart: unless-stopped
    ports:
      - "8017:8080"
   #depends_on:
     #app:
       #condition: service_healthy
    networks:
      - govi-m
    volumes:
      - app-data:/var/www:ro
    user: nginxuser

# Networks
networks:
  govi-m:
    driver: bridge

volumes:
  app-data:
